name: Release Zarf Package

on:
  schedule:
    - cron: "15 4 * * *"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  info:
    name: Determine build info
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Determine Build Tag
        id: tag
        env:
          sha: ${{ github.sha }}
          job: ${{ github.run_number }}
        run: |-
          echo "TAG=$(echo $job-${sha:0:8})" >> $GITHUB_OUTPUT

      - name: Get Git Tag Info
        id: git-tag
        run: |-
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            echo "tag=$(echo ${{ github.ref }} | sed 's!refs/tags/!!g')"
            echo "tag=$(echo ${{ github.ref }} | sed 's!refs/tags/!!g')" >> $GITHUB_OUTPUT
          else
            echo "TAG=''"
            echo "TAG=''" >> $GITHUB_OUTPUT
          fi

      - name: Output version
        id: determine
        run: |-
          if [[ "${{ steps.git-tag.outputs.TAG }}" != "''" ]]; then
            echo "version=${{ steps.git-tag.outputs.TAG }}"
            echo "version=${{ steps.git-tag.outputs.TAG }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ steps.tag.outputs.TAG }}"
            echo "version=${{ steps.tag.outputs.TAG }}" >> $GITHUB_OUTPUT
          fi
    outputs:
      tag: ${{ steps.determine.outputs.version }}

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    needs:
      - info
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        flavor:
          - minimus
          - upstream
        pkgs:
          - init-local-path
          - init-ceph
        arch:
          - amd64
          - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Determine Build Tag
        id: tag
        env:
          sha: ${{ github.sha }}
          job: ${{ github.run_number }}
        run: |-
          echo "version=$(yq '.metadata.version' ${{ matrix.flavor }}/${{ matrix.pkgs }}/uds-bundle.yaml)" >> $GITHUB_OUTPUT

      - name: Install The Latest Release Version of UDS
        uses: defenseunicorns/setup-uds@ab842abcad1f7a3305c2538e3dd1950d0daacfa5 # v1.0.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package UDS package, version
        run: |-
          uds create --confirm \
            ${{ matrix.flavor }}/${{ matrix.pkgs }} \
            --no-progress \
            --signing-key env://COSIGN_KEY \
            --signing-key-password ${{ secrets.COSIGN_PASS }} \
            --architecture ${{ matrix.arch }} \
            --version ${{ steps.tag.outputs.version }}-${{ matrix.flavor }} \
            --output .
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}

      - name: Package UDS package, commit
        run: |-
          uds create --confirm \
            ${{ matrix.flavor }}/${{ matrix.pkgs }} \
            --no-progress \
            --signing-key env://COSIGN_KEY \
            --signing-key-password ${{ secrets.COSIGN_PASS }} \
            --architecture ${{ matrix.arch }} \
            --version ${{ steps.tag.outputs.version }}-${{ needs.info.outputs.tag }}-${{ matrix.flavor }} \
            --output .
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}

      - name: Publish UDS package
        run: |-
          find . -iname "*.tar.zst" -exec uds publish --no-progress '{}' oci://ghcr.io/${{ github.repository_owner }}/uds \;
